services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate &&  python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - static_volume:/code/static
    depends_on:
      db:
        condition: service_healthy



  db:
    image: postgres:17.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"




volumes:
  postgres_data:
  static_volume:
