# Generated by Django 5.2.6 on 2025-09-06 15:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20,
                                                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                                                verbose_name='баланс')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_ad', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount',
                 models.DecimalField(decimal_places=2, max_digits=20,
                                     validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('operation_type', models.CharField(choices=[('DEPOSIT', 'Пополнение'), ('WITHDRAW', 'Снятие')],
                                                    help_text='Выберите тип операции', max_length=10,
                                                    verbose_name='Тип операции')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet',
                                             verbose_name='Кошелек')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
