# Generated by Django 5.2.6 on 2025-09-06 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
